server.port=8761

logging.charset.console=UTF-8

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.registerWithEureka:false
eureka.client.fetchRegistry:false
eureka.instance.prefer-ip-address=true
spring.cloud.inetutils.preferred-network=192.168
