#spring.application.name=gateway-service

server.port=9004

#zuul.routes.microservice-produits.url = http://localhost:9001/microservice-produits
management.endpoints.web.expose=info, health, refresh

#Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.server.webflux.routes.builder.RouteLocatorBuilder=enabled
spring.cloud.gateway.server.webflux.routes[0].id=0
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:9001/
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/Produits/**

spring.cloud.gateway.routes[0].id=produitsModule
spring.cloud.gateway.routes[0].uri=http://localhost:9001/
spring.cloud.gateway.routes[0].predicates[0]=Path=/Produits/**
spring.cloud.gateway.routes[0].filters[0]:RewritePath=/service(?<segmeproduitsModulent>/?.*), $\{segment}
spring.cloud.gateway.routes[0].filters[0].name=Logging
spring.cloud.gateway.routes[0].filters[0].args.baseMessage= My Custom Message
spring.cloud.gateway.routes[0].filters[0].args.baseMessage.preLogger=true
spring.cloud.gateway.routes[0].filters[0].args.baseMessage.postLogger=true
management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=*

logging.charset.console=UTF-8

#Spring Security
spring.security.user.name=user
spring.security.user.password=password

##spring.security.oauth22.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/myrealm
#spring.security.oauth22.resourceserver.jwt.jwk-set-uri:http://localhost:8080/realms/demo/protocol/openid-connect/certs
#spring.security.oauth22.resourceserver.jwt.jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs
#spring.security.oauth22.client.provider.keycloak.token-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/token
#spring.security.oauth22.client.provider.keycloak.authorization-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/auth
#spring.security.oauth22.client.provider.keycloak.user-info-uri: http://localhost:8080/auth/realms/master/protocol/openid-connect/userinfo
#spring.security.oauth22.client.provider.keycloak.user-name-attribute: preferred_username

#spring.security.oauth22.client.provider.registration.client-id.keycloak-with-test-scope.provider=keycloak
#spring.security.oauth22.client.provider.registration.client-id.keycloak-with-test-scope.client-id=spring-with-test-scope
#spring.security.oauth22.client.provider.registration.client-id.keycloak-with-test-scope.client-secret=O02DldZGdIL5UpcXmXS2RSHsvGo1Ocwq
#spring.security.oauth22.client.provider.registration.client-id.keycloak-with-test-scope.authorization-grant-type=authorization_code
#spring.security.oauth22.client.provider.registration.client-id.keycloak-with-test-scope.redirect-uri="{baseUrl}/login/oauth2/code/keycloak"

#spring.security.oauth22.client.provider.registration.client-id.keycloak-without-test-scope.provider=keycloak
#spring.security.oauth22.client.provider.registration.client-id.keycloak-without-test-scope.client-id=spring-without-test-scope
#spring.security.oauth22.client.provider.registration.client-id.keycloak-without-test-scope.client-secret=f6fc369d-49ce-4132-8282-5b5d413eba23
#spring.security.oauth22.client.provider.registration.client-id.keycloak-without-test-scope.authorization-grant-type=authorization_code
#spring.security.oauth22.client.provider.registration.client-id.keycloak-without-test-scope.redirect-uri="{baseUrl}/login/oauth2/code/keycloak"



logging.level.org.springframework.cloud.gateway= DEBUG
logging.level.org.springframework.security: DEBUG
logging.level.org.springframework.web.reactive.function.client: TRACE
