server.port=9005

management.endpoints.web.exposure.include=refresh

#Configurations H2
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

#management.endpoints.web.expose=info, health, refresh
management.endpoints.web.exposure.include=health,info,metrics,env
management.info.env.enabled = true
info.app-author = Patrick VALERI
info.app-license = License en cours

#Eureka
eureka.client.serviceUrl.defaultZone:http://localhost:8761/eureka/
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true

#Ribbon
microservice-produits.ribbon.listOfServers=localhost:9001,localhost:9011,localhost:9002
server.ribbon.ServerListRefreshInterval=1000

#swagger3 
springdoc.api-docs.path=/api-docs
