server.port=9000

management.endpoints.web.exposure.include=refresh

#Configurations H2
spring.jpa.show-sql=true
spring.h2.console.enabled=true

#Eureka
eureka.client.serviceUrl.defaultZone:http://localhost:8761/eureka/
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true

#Ribbon
microservice-produits.ribbon.listOfServers=localhost:9001,localhost:9011
server.ribbon.ServerListRefreshInterval=1000

#spring.cloud.openfeign.client.config.microservice-commandes.url="http://localhost:9002"

#swagger3 
springdoc.api-docs.path=/api-docs

#Spring Security
spring.security.user.name=user
spring.security.user.password=password
